# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: rsgrants

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
  - wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: desc
  filters:
    exclude:
      - '^Merge'

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  - ids:
      - rsgrants
    image_templates:
      - "ghcr.io/goodwaygroup/rsgrants:{{ .RawVersion }}"
      - "ghcr.io/goodwaygroup/rsgrants:latest"

brews:
  - tap:
      owner: GoodwayGroup
      name: homebrew-rsgrants
    homepage: "https://goodwaygroup.github.io/rsgrants/"
    description: "A set of commands to audit AWS usage to identify cost savings and security issues."
    license: "MIT"
    test: |
      system "#{bin}/rsgrants --help"
    install: |
      bin.install "rsgrants"
